name: Terraform + OPA Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform_opa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install OPA
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.27.0/conftest_0.27.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.27.0_Linux_x86_64.tar.gz
          mv conftest /usr/local/bin

      - name: Run Terraform Commands
        run: |
          cd terraform
          terraform init
          terraform validate
          terraform plan --out tfplan.binary
          terraform show -json tfplan.binary > tfplan.json

      - name: Run OPA Policy Checks
        run: |
          conftest test -p opa .

